### ISSUE TITLE
可以连接设备 但是无法opennotify

### ISSUE THREAD

**Issue by sdjwj1118** [zqisheng/QsBle#5]
private fun connect(mac: String) {
        QsBle.getInstance().addConnectStatusChangeCallback(
            mac
        ) { _, isConnect, _, _ ->
            if (isConnect) {
                Logger.i("蓝牙已连接")
                QsBle.getInstance().openNotify(
                    mac,
                    UUID.fromString(BleConstant.SERVICE_UUID),
                    UUID.fromString(BleConstant.NOTIFY_UUID)
                )
            }
        }
        QsBle.getInstance().addNotifyFailCallback(
            mac
        ) { _, status ->
            Logger.i("status:${status}")
        }
        QsBle.getInstance().addNotifyStatusCallback(
            mac
        ) { _, _, notifyEnable ->
            if (notifyEnable) {
                Logger.i("通道已创建")
                QsBle.getInstance().writeByLock(mac, LoginCmd(AppCache.device?.devicePwd).build())
            }
        }
        QsBle.getInstance().connect(mac)
    }

ConnectStatusChangeCallback是有回调的  我在连接成功后去打开通道 NotifyStatusCallback一直没有被回调到 NotifyFailCallback也没有被回调到，notifyuuid确定没问题 因为在用fastble框架是能打开监听通道的

**Comment by zqisheng** [comment]
你用这个tag过滤一下日志,发给我看看,排查一下问题:
BleCallback

**Comment by sdjwj1118** [comment]
要开启debug模式吗

**Comment by sdjwj1118** [comment]
2022-09-17 18:15:16.628 15589-15667/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnConnectionStateMessage.onHandlerMessage(OnConnectionStateMessage.java:40) ]
    BleCallback OnConnectionStateMessage:mac=A4:C1:38:C2:A0:3A,status=0,profileState=2
2022-09-17 18:15:17.070 15589-15667/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnConnectionUpdatedMessage.onHandlerMessage(OnConnectionUpdatedMessage.java:38) ]
    BleCallback OnConnectionUpdatedMessage:mac=A4:C1:38:C2:A0:3A,interval=6,latency=0,timeout=500,status=0
2022-09-17 18:15:17.929 15589-15667/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnServicesDiscoveredMessage.onHandlerMessage(OnServicesDiscoveredMessage.java:42) ]
    BleCallback OnServicesDiscoveredMessage:mac=A4:C1:38:C2:A0:3A,status=0,services=[00001800-0000-1000-8000-00805f9b34fb,00001801-0000-1000-8000-00805f9b34fb,0000180a-0000-1000-8000-00805f9b34fb,0000180f-0000-1000-8000-00805f9b34fb,0000fd50-0000-1000-8000-00805f9b34fb,00010203-0405-0607-0809-0a0b0c0d1912,]
2022-09-17 18:15:18.014 15589-15667/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnConnectionUpdatedMessage.onHandlerMessage(OnConnectionUpdatedMessage.java:38) ]
    BleCallback OnConnectionUpdatedMessage:mac=A4:C1:38:C2:A0:3A,interval=36,latency=0,timeout=500,status=0

**Comment by zqisheng** [comment]
QsBle.getInstance().addServicesDiscoveredCallback()
你在这个方法回调中添加打开通知的操作,因为设备连接之后,发现服务需要时间,设备服务没有发现之前是无法对特征值进行操作的

**Comment by sdjwj1118** [comment]
已解决 再问另外个问题，组包器是否能够不重写getPkgIndex方法 因为协议定义上没有定义包序号，只校验头部和尾部以及crc

**Comment by zqisheng** [comment]
你只需要实现这个接口就行了com.zqs.ble.core.api.IMultiPackageAssembly
com.zqs.ble.core.api.BaseMultiPackageAssembly这个组包类也是IMultiPackageAssembly的子类,参照BaseMultiPackageAssembly的实现方法就可以了

**Comment by sdjwj1118** [comment]
反馈一个问题 通过qsble成功连接上了设备 并且也打开了通知监听 然后才发送消息，但是蓝牙收不到消息，其他框架目前是可以发送的。日志如下
2022-09-20 16:35:48.698 11062-11130/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnConnectionStateMessage.onHandlerMessage(OnConnectionStateMessage.java:40) ]
    BleCallback OnConnectionStateMessage:mac=46:89:39:C6:4D:5A,status=0,profileState=2
2022-09-20 16:35:49.138 11062-11130/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnConnectionUpdatedMessage.onHandlerMessage(OnConnectionUpdatedMessage.java:38) ]
    BleCallback OnConnectionUpdatedMessage:mac=46:89:39:C6:4D:5A,interval=6,latency=0,timeout=500,status=0
2022-09-20 16:35:49.199 11062-11130/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnServicesDiscoveredMessage.onHandlerMessage(OnServicesDiscoveredMessage.java:42) ]
    BleCallback OnServicesDiscoveredMessage:mac=46:89:39:C6:4D:5A,status=0,services=[00001800-0000-1000-8000-00805f9b34fb,0000ae00-0000-1000-8000-00805f9b34fb,]
2022-09-20 16:35:49.219 11062-11130/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnDescriptorWriteMessage.onHandlerMessage(OnDescriptorWriteMessage.java:46) ]
    BleCallback OnDescriptorWriteMessage:mac=46:89:39:C6:4D:5A,status=0,chac=0000ae02-0000-1000-8000-00805f9b34fb,desc=00002902-0000-1000-8000-00805f9b34fb,value=0100
2022-09-20 16:35:49.243 11062-11130/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnCharacteristicWriteMessage.onHandlerMessage(OnCharacteristicWriteMessage.java:39) ]
    BleCallback OnCharacteristicWriteMessage:mac=46:89:39:C6:4D:5A,status=3,chac=0000ae01-0000-1000-8000-00805f9b34fb,value=2222011038623261636239373465353036626661
2022-09-20 16:35:49.265 11062-11130/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnCharacteristicWriteMessage.onHandlerMessage(OnCharacteristicWriteMessage.java:39) ]
    BleCallback OnCharacteristicWriteMessage:mac=46:89:39:C6:4D:5A,status=3,chac=0000ae01-0000-1000-8000-00805f9b34fb,value=2222011038623261636239373465353036626661
2022-09-20 16:35:49.272 11062-11130/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnConnectionUpdatedMessage.onHandlerMessage(OnConnectionUpdatedMessage.java:38) ]
    BleCallback OnConnectionUpdatedMessage:mac=46:89:39:C6:4D:5A,interval=36,latency=0,timeout=500,status=0
2022-09-20 16:35:49.363 11062-11130/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnCharacteristicWriteMessage.onHandlerMessage(OnCharacteristicWriteMessage.java:39) ]
    BleCallback OnCharacteristicWriteMessage:mac=46:89:39:C6:4D:5A,status=3,chac=0000ae01-0000-1000-8000-00805f9b34fb,value=2222011038623261636239373465353036626661
2022-09-20 16:35:49.453 11062-11130/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnCharacteristicWriteMessage.onHandlerMessage(OnCharacteristicWriteMessage.java:39) ]
    BleCallback OnCharacteristicWriteMessage:mac=46:89:39:C6:4D:5A,status=3,chac=0000ae01-0000-1000-8000-00805f9b34fb,value=2222011038623261636239373465353036626661
2022-09-20 16:35:49.742 11062-11130/com.shqj.saas.client D/QsBle: [ Thread:Thread-4, at com.zqs.ble.core.deamon.message.callback.OnConnectionUpdatedMessage.onHandlerMessage(OnConnectionUpdatedMessage.java:38) ]
    BleCallback OnConnectionUpdatedMessage:mac=46:89:39:C6:4D:5A,interval=24,latency=10,timeout=600,status=0

**Comment by zqisheng** [comment]
日志上写的状态码status=3,你这个写特征值的状态返回的错误码是android.bluetooth.BluetoothGatt#GATT_WRITE_NOT_PERMITTED,这个是特征值没有写权限的意思
可能情况:
1.你特征值uuid设置错了,把notify的特征值设置成了write的特征值
2.设备那边没有把write特征值赋予可写的权限

**Comment by sdjwj1118** [comment]
你好作者，我再次确认了下writeuuid是没有错的
![image](https://user-images.githubusercontent.com/33438073/191217893-c4c92f1e-05ee-44e0-a4b7-6839cfd86ad4.png)
用blemanager是能正常发送数据

**Comment by zqisheng** [comment]
那你把blemanager的日志发我看看

**Comment by sdjwj1118** [comment]
![image](https://user-images.githubusercontent.com/33438073/191223007-240c80d4-16ec-4634-a6f7-cac029166d2d.png)

**Comment by zqisheng** [comment]
你把fastble的write数据的日志都过滤发我看看

**Comment by zqisheng** [comment]
你顺便用writeByLockNoRsp这种方式write特征值试试,有可能是你的设备不支持Rsp类型的写

**Comment by sdjwj1118** [comment]
验证了下 writeByLockNoRsp该方法可以发送数据 但是从串口来看 数据尾部会有多余的00000
![image](https://user-images.githubusercontent.com/33438073/191226039-22dee465-6ad8-4e00-89cc-bef11300400f.png)
shi'ji实际上我的指令知道AA结束

**Comment by zqisheng** [comment]
那就是你的设备的write特征值不支持rsp类型的写,补0是正常的,ble的最小发送单元式20byte,不够20字节,框架自动补0

**Comment by sdjwj1118** [comment]
那么在分包的情况下 writeByLockNoRsp方法会把分的包按顺序发送吗 之前用fastble 那个框架发送有个问题 比如我第一个包分成了3个 他发了第 1 2 个的时候 app又发了一条指令 他会穿插到2 和 3之间 相当于顺序是  1 2 其他 3 这样

**Comment by zqisheng** [comment]
只要你对一个设备write特征值用的都是write方法都带lock的,都是按顺序发的,不会出现乱包

**Comment by sdjwj1118** [comment]
ok 感谢作者，有序有问题再反馈
