### ISSUE TITLE
出现栈溢出，会有崩溃的情况，具体可以联系我邮箱 2891794846@qq.com

### ISSUE THREAD

**Issue by AndroidCoolMan** [zqisheng/QsBle#9]
java.lang.StackOverflowError: stack size 991KB
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1226)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:216)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:294)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:125)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
        at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.awake(DefaultMessageLooper.java:126)
	at com.zqs.ble.core.deamon.DefaultMessageLooper.sendMessage(DefaultMessageLooper.java:327)
	at com.zqs.ble.impl.DefaultBleMessageSender.sendMessage(DefaultBleMessageSender.java:27)
	at com.zqs.ble.core.SimpleBle.sendMessage(SimpleBle.java:319)
	at com.zqs.ble.core.callback.BleGattCallback.sendMessage(BleGattCallback.java:189)
	at com.zqs.ble.core.callback.BleGattCallback.onWrapCharacteristicWrite(BleGattCallback.java:62)
	at com.zqs.ble.core.callback.BleGattCallback.onCharacteristicWrite(BleGattCallback.java:136)
	at android.bluetooth.BluetoothGatt$1$8.run(BluetoothGatt.java:525)
	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:964)
	at android.bluetooth.BluetoothGatt.access$600(BluetoothGatt.java:48)
	at android.bluetooth.BluetoothGatt$1.onCharacteristicWrite(BluetoothGatt.java:520)
	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:282)
	at android.os.Binder.execTransactInternal(Binder.java:1220)
	at android.os.Binder.execTransact(Binder.java:1179)

**Comment by zqisheng** [comment]
你好,你这边是不是初始化的时候是不是用的是第二种方式初始化的?
![image](https://github.com/zqisheng/QsBle/assets/34211476/ba0391c6-5015-42f8-ab7a-883ba1131364)

**Comment by zqisheng** [comment]
最新的1.2.5版本应该解决了栈溢出的问题

**Comment by AndroidCoolMan** [comment]
厉害，今天周末出来玩了，明天我看下9再回你哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月12日(周日) 下午5:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zqisheng/QsBle] 出现栈溢出，会有崩溃的情况，具体可以联系我邮箱 ***@***.*** (Issue #9)




 
最新的1.2.5版本应该解决了栈溢出的问题

**Comment by AndroidCoolMan** [comment]
你好，我之前使用的是1.2.3的版本，初始化的方式使用的也是推荐的方式一的  QsBle.getInstance().init(BaseApp.app.applicationContext)。
现在我使用最新的V1.2.6版本之后，发现我原本要发送的数据，比如是data = 01 02 09 03 14 6C 03 9F 3B 02 B2 D4 F5，结果在GlobalBleCallback 的回调方法中 override fun onCharacteristicWrite(
        mac: String?,
        characteristic: BluetoothGattCharacteristic?,
        status: Int
    )打印出来写的数据characteristic 长度是255个字节，除了原始data数据之外，其余全部是补位00，请问下 是因为V1.2.6修改了mtu的原因吗？以前的V1.2.3不会这样，这样会导致我发送 的数据不按照既定协议了，导致发送数据接收方无法识别并响应
